# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_uesr', '0002_auto_20180924_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.ImageField(default='user/201809/23/tx1.png', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
