# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_uesr', '0004_auto_20180924_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.ImageField(default='user/201809/24/1_6WrFswI.jpg', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
