# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sup_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityzonegoods',
            options={'verbose_name': '活动专区商品', 'verbose_name_plural': '活动专区商品'},
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情'),
        ),
    ]
